export const CAPABILITIES = {
  STS_READ: "STS_READ",
  STS_WRITE: "STS_WRITE",
  STS_ADMIN: "STS_ADMIN",
  TM_READ: "TM_READ",
  PLANNER: "PLANNER",
  CASE_ASSIGN: "CASE_ASSIGN",
  BACKOFFICE_RESTRICTED: "BACKOFFICE_RESTRICTED",
  VIDEOS_ONLY: "VIDEOS_ONLY",
  OWN_CASES_ONLY: "OWN_CASES_ONLY",
  VIDEO_GROUPS_ADMIN: "VIDEO_GROUPS_ADMIN",
  FORCE_PASSWORD_CHANGE: "FORCE_PASSWORD_CHANGE",
} as const;

export type Capability = (typeof CAPABILITIES)[keyof typeof CAPABILITIES];
